name: Back-end build and deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build with Maven
        run: |
          mvn clean package
          echo "begin copy ruoyi-gateway "
          cp ./ruoyi-gateway/target/ruoyi-gateway.jar ./docker/ruoyi/gateway/jar
          echo "begin copy ruoyi-auth "
          cp ./ruoyi-auth/target/ruoyi-auth.jar ./docker/ruoyi/auth/jar
          echo "begin copy ruoyi-modules-system "
          cp ./ruoyi-modules/ruoyi-system/target/ruoyi-modules-system.jar ./docker/ruoyi/modules/system/jar
          echo "begin copy ruoyi-modules-item "
          cp ./ruoyi-modules/item/target/item.jar ./docker/ruoyi/modules/item/jar
          echo "begin copy ruoyi-modules-order "
          cp ./ruoyi-modules/order/target/order.jar ./docker/ruoyi/modules/order/jar
          echo "begin copy ruoyi-modules-details "
          cp ./ruoyi-modules/details/target/details.jar ./docker/ruoyi/modules/details/jar

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      
      - name: Build gateway and Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/ruoyi/gateway
          push: true
          tags: ${{ secrets.USERNAME }}/gateway:v1

      - name: Build auth and Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/ruoyi/auth
          push: true
          tags: ${{ secrets.USERNAME }}/auth:v1

      - name: Build modules-system and Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/ruoyi/modules/system
          push: true
          tags: ${{ secrets.USERNAME }}/modules-system:v1

      - name: Build item and Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/ruoyi/modules/item
          push: true
          tags: ${{ secrets.USERNAME }}/modules-item:v1

      - name: Build order and Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/ruoyi/modules/order
          push: true
          tags: ${{ secrets.USERNAME }}/modules-order:v1

      - name: Build details and Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/ruoyi/modules/details
          push: true
          tags: ${{ secrets.USERNAME }}/modules-details:v1

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$EC2_GATEWAY" >> ~/.ssh/known_hosts
          ssh-keyscan -H "$EC2_AUTH" >> ~/.ssh/known_hosts
          ssh-keyscan -H "$EC2_SYSTEM" >> ~/.ssh/known_hosts
          ssh-keyscan -H "$EC2_ITEM" >> ~/.ssh/known_hosts
          ssh-keyscan -H "$EC2_ORDER" >> ~/.ssh/known_hosts
          ssh-keyscan -H "$EC2_DETAILS" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_GATEWAY: ${{ secrets.EC2_GATEWAY }}
          EC2_AUTH: ${{ secrets.EC2_AUTH }}
          EC2_SYSTEM: ${{ secrets.EC2_SYSTEM }}
          EC2_ITEM: ${{ secrets.EC2_ITEM }}
          EC2_ORDER: ${{ secrets.EC2_ORDER }}
          EC2_DETAILS: ${{ secrets.EC2_DETAILS }}

      # docker run --network="host" --name ruoyi-gateway -p 8080:8080 -d linfan1130/gateway:v1
      - name: Deploy gateway to Cloud
        working-directory: docker/ruoyi/gateway
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST "docker pull $USERNAME/gateway:v1"
        env:
          EC2_HOST: ${{ secrets.EC2_GATEWAY }}
          USERNAME: ${{ secrets.USERNAME }}

      # docker run --network="host" --name ruoyi-auth -p 9200:9200 -d linfan1130/auth:v1
      - name: Deploy auth to Cloud
        working-directory: docker/ruoyi/auth
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST "docker pull $USERNAME/auth:v1"
        env:
          EC2_HOST: ${{ secrets.EC2_AUTH }}
          USERNAME: ${{ secrets.USERNAME }}

      # docker run --network="host" --name ruoyi-system -p 9201:9201 -d linfan1130/modules-system:v1
      - name: Deploy modules-system to Cloud
        working-directory: docker/ruoyi/modules/system
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST "docker pull $USERNAME/modules-system:v1"
        env:
          EC2_HOST: ${{ secrets.EC2_SYSTEM }}
          USERNAME: ${{ secrets.USERNAME }}

      # docker run --network="host" --name item -p 8100:8100 -d linfan1130/modules-item:v1
      - name: Deploy modules-items to Cloud
        working-directory: docker/ruoyi/modules/item
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST "docker pull $USERNAME/modules-item:v1"
        env:
          EC2_HOST: ${{ secrets.EC2_ITEM }}
          USERNAME: ${{ secrets.USERNAME }}

      # docker run --network="host" --name order -p 8101:8101 -d linfan1130/modules-order:v1
      - name: Deploy modules-order to Cloud
        working-directory: docker/ruoyi/modules/order
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST "docker pull $USERNAME/modules-order:v1"
        env:
          EC2_HOST: ${{ secrets.EC2_ORDER }}
          USERNAME: ${{ secrets.USERNAME }}

      # docker run --network="host" --name details -p 8102:8102 -d linfan1130/modules-details:v1
      - name: Deploy modules-details to Cloud
        working-directory: docker/ruoyi/modules/details
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST "docker pull $USERNAME/modules-details:v1"
        env:
          EC2_HOST: ${{ secrets.EC2_DETAILS }}
          USERNAME: ${{ secrets.USERNAME }}
