name: Back-end build and deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build MySQL and Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/mysql
          push: true
          tags: ${{ secrets.USERNAME }}/mysql:v1

      - name: Build Nacos and Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/nacos
          push: true
          tags: ${{ secrets.USERNAME }}/nacos:v1

      - name: Build Redis and Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/redis
          push: true
          tags: ${{ secrets.USERNAME }}/redis:v1

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_MYSQL }}

      # docker run --name mysql -e MYSQL_ROOT_PASSWORD=password -p 3306:3306 -d $USERNAME/mysql:v1
      - name: Deploy MySQL to Cloud
        working-directory: docker/mysql
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST "docker pull $USERNAME/mysql:v1"
        env:
          EC2_HOST: ${{ secrets.EC2_MYSQL }}
          USERNAME: ${{ secrets.USERNAME }}

      # docker run --name nacos-server -e MODE=standalone -p 8848:8848 -d $USERNAME/nacos:v1
      - name: Deploy Nacos to Cloud
        working-directory: docker/nacos
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST "docker pull $USERNAME/nacos:v1"
        env:
          EC2_HOST: ${{ secrets.EC2_NACOS }}
          USERNAME: ${{ secrets.USERNAME }}

      # docker run --name redis -p 6379:6379 -d $USERNAME/redis:v1
      - name: Deploy Redis to Cloud
        working-directory: docker/redis
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST "docker pull $USERNAME/redis:v1"
        env:
          EC2_HOST: ${{ secrets.EC2_REDIS }}
          USERNAME: ${{ secrets.USERNAME }}

      # - name: Build with Maven
      #   working-directory: backend-module
      #   run: |
      #     mvn clean package
      #     docker build -t image
